"""add officer verified qualification facts

Revision ID: 0d6693b04f11
Revises: 7c5ec29dcde4
Create Date: 2026-08-10 10:29:23.216607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6693b04f11'
down_revision = '7c5ec29dcde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'verified_education_level',
            sa.String(length=30),
            nullable=True,
        ))

    op.execute(
        sa.text(
            "UPDATE officers "
            "SET verified_military_months = 0 "
            "WHERE verified_military_months IS NULL"
        )
    )

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.alter_column(
            'verified_military_months',
            existing_type=sa.INTEGER(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.alter_column('verified_military_months',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('verified_education_level')

    # ### end Alembic commands ###
