"""v0.2.12 add peace officer proficiency inputs

Revision ID: 0eab4d39ee73
Revises: a0a5cf4ff7bf
Create Date: 2026-08-09 13:48:05.010777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eab4d39ee73'
down_revision = 'a0a5cf4ff7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peace_officer_service_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('verified_military_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('verified_military_months')
        batch_op.drop_column('peace_officer_service_start_date')

    # ### end Alembic commands ###
