"""v0.1.9 add TCOLE training credits

Revision ID: 1fda256cca0e
Revises: 6dd7b36fa55e
Create Date: 2026-08-08 11:50:48.656472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fda256cca0e'
down_revision = '6dd7b36fa55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('training_record_id', sa.Uuid(), nullable=False),
    sa.Column('course_number', sa.String(length=50), nullable=False),
    sa.Column('course_date', sa.Date(), nullable=False),
    sa.Column('credited_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('role_snapshot', sa.String(length=255), nullable=True),
    sa.Column('reported_total_text', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['training_record_id'], ['training_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'training_record_id', 'course_number', 'course_date', 'credited_hours', 'role_snapshot', name='uq_training_credit')
    )
    with op.batch_alter_table('training_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_credits_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_credits_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_credits_training_record_id'), ['training_record_id'], unique=False)

    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credited_hours', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('hours_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_column('hours_source')
        batch_op.drop_column('credited_hours')

    with op.batch_alter_table('training_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_credits_training_record_id'))
        batch_op.drop_index(batch_op.f('ix_training_credits_officer_id'))
        batch_op.drop_index(batch_op.f('ix_training_credits_agency_id'))

    op.drop_table('training_credits')
    # ### end Alembic commands ###
