"""v0.1.5 expand import job tracking

Revision ID: 4548b5aca5bd
Revises: f81baec4d098
Create Date: 2026-08-08 11:31:56.759858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4548b5aca5bd'
down_revision = 'f81baec4d098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_award_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('skipped_course_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('skipped_course_count')
        batch_op.drop_column('skipped_award_count')

    # ### end Alembic commands ###
