"""v0.1.3 add officer awards

Revision ID: 4882e6f4c3c8
Revises: 702a4283e2d9
Create Date: 2026-08-08 11:27:41.420567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4882e6f4c3c8'
down_revision = '702a4283e2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_awards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=False),
    sa.Column('award_name', sa.String(length=255), nullable=False),
    sa.Column('award_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'officer_id', 'award_type', 'award_name', 'award_date', name='uq_officer_award')
    )
    with op.batch_alter_table('officer_awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officer_awards_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_awards_officer_id'), ['officer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officer_awards_officer_id'))
        batch_op.drop_index(batch_op.f('ix_officer_awards_agency_id'))

    op.drop_table('officer_awards')
    # ### end Alembic commands ###
