"""v0.1.6 add import summary counts

Revision ID: 6dd7b36fa55e
Revises: 4548b5aca5bd
Create Date: 2026-08-08 11:33:43.501342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd7b36fa55e'
down_revision = '4548b5aca5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_rows_processed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('course_rows_processed', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('course_rows_processed')
        batch_op.drop_column('award_rows_processed')

    # ### end Alembic commands ###
