"""add jailer service dates and import counters

Revision ID: 6e7f6899b7ed
Revises: 8ed47812a181
Create Date: 2026-08-10 14:51:43.590040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7f6899b7ed'
down_revision = '8ed47812a181'
branch_labels = None
depends_on = None


def upgrade():
    # Add nullable counters first so existing import-job rows
    # remain valid during the migration.
    with op.batch_alter_table(
        'import_jobs',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'jailer_license_rows',
                sa.Integer(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                'jailer_service_dates_populated',
                sa.Integer(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                'jailer_service_dates_updated',
                sa.Integer(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                'jailer_service_dates_unchanged',
                sa.Integer(),
                nullable=True,
            )
        )

    # Historical imports predate Jailer tracking, so their
    # Jailer counters are correctly initialized to zero.
    op.execute(
        sa.text(
            "UPDATE import_jobs SET "
            "jailer_license_rows = 0, "
            "jailer_service_dates_populated = 0, "
            "jailer_service_dates_updated = 0, "
            "jailer_service_dates_unchanged = 0 "
            "WHERE jailer_license_rows IS NULL "
            "OR jailer_service_dates_populated IS NULL "
            "OR jailer_service_dates_updated IS NULL "
            "OR jailer_service_dates_unchanged IS NULL"
        )
    )

    with op.batch_alter_table(
        'import_jobs',
        schema=None,
    ) as batch_op:
        batch_op.alter_column(
            'jailer_license_rows',
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.alter_column(
            'jailer_service_dates_populated',
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.alter_column(
            'jailer_service_dates_updated',
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.alter_column(
            'jailer_service_dates_unchanged',
            existing_type=sa.Integer(),
            nullable=False,
        )

    with op.batch_alter_table(
        'officers',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'jailer_service_start_date',
                sa.Date(),
                nullable=True,
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('jailer_service_start_date')

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('jailer_service_dates_unchanged')
        batch_op.drop_column('jailer_service_dates_updated')
        batch_op.drop_column('jailer_service_dates_populated')
        batch_op.drop_column('jailer_license_rows')

    # ### end Alembic commands ###
