"""v0.1.1 database foundation

Revision ID: 702a4283e2d9
Revises: 
Create Date: 2026-08-08 11:21:17.230435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702a4283e2d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tcole_agency_number', sa.String(length=50), nullable=True),
    sa.Column('ori', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('awards_filename', sa.String(length=255), nullable=True),
    sa.Column('courses_filename', sa.String(length=255), nullable=True),
    sa.Column('officer_count', sa.Integer(), nullable=False),
    sa.Column('award_count', sa.Integer(), nullable=False),
    sa.Column('course_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_agency_id'), ['agency_id'], unique=False)

    op.create_table('officers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('tcole_pid', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('employment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'tcole_pid', name='uq_officers_agency_tcole_pid')
    )
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officers_agency_id'), ['agency_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officers_agency_id'))

    op.drop_table('officers')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_agency_id'))

    op.drop_table('import_jobs')
    op.drop_table('agencies')
    # ### end Alembic commands ###
