"""v0.2.6 add officer credential verifications

Revision ID: 839ec7ee925d
Revises: c903caf2dcff
Create Date: 2026-08-08 13:35:06.380238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839ec7ee925d'
down_revision = 'c903caf2dcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_credential_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'officer_id', 'credential_type', 'verified_at', name='uq_officer_credential_verification')
    )
    with op.batch_alter_table('officer_credential_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officer_credential_verifications_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_credential_verifications_credential_type'), ['credential_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_credential_verifications_officer_id'), ['officer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_credential_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officer_credential_verifications_officer_id'))
        batch_op.drop_index(batch_op.f('ix_officer_credential_verifications_credential_type'))
        batch_op.drop_index(batch_op.f('ix_officer_credential_verifications_agency_id'))

    op.drop_table('officer_credential_verifications')
    # ### end Alembic commands ###
