"""add verified jailer cultural diversity exemption

Revision ID: 8ed47812a181
Revises: 0d6693b04f11
Create Date: 2026-08-10 12:58:53.183653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed47812a181'
down_revision = '0d6693b04f11'
branch_labels = None
depends_on = None


def upgrade():
    # Add nullable first so existing officer rows remain valid.
    with op.batch_alter_table(
        'officers',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'verified_jailer_cultural_diversity_exemption',
                sa.Boolean(),
                nullable=True,
            )
        )

    # Existing officers default to no verified exemption.
    op.execute(
        sa.text(
            "UPDATE officers "
            "SET verified_jailer_cultural_diversity_exemption = FALSE "
            "WHERE verified_jailer_cultural_diversity_exemption "
            "IS NULL"
        )
    )

    # The application requires an explicit Boolean thereafter.
    with op.batch_alter_table(
        'officers',
        schema=None,
    ) as batch_op:
        batch_op.alter_column(
            'verified_jailer_cultural_diversity_exemption',
            existing_type=sa.Boolean(),
            nullable=False,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('verified_jailer_cultural_diversity_exemption')

    # ### end Alembic commands ###
