"""add officer name suffix

Revision ID: 9fc44bb0643f
Revises: 6e7f6899b7ed
Create Date: 2026-08-10 15:16:28.357923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc44bb0643f'
down_revision = '6e7f6899b7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('suffix')

    # ### end Alembic commands ###
