"""v0.2.11 add agency email convention and officer override

Revision ID: a0a5cf4ff7bf
Revises: 839ec7ee925d
Create Date: 2026-08-09 10:54:26.402506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a5cf4ff7bf'
down_revision = '839ec7ee925d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_pattern', sa.String(length=50), nullable=True))

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_override', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('email_override')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('email_pattern')
        batch_op.drop_column('email_domain')

    # ### end Alembic commands ###
