"""v0.2.3 add officer assignments and archival lifecycle

Revision ID: c903caf2dcff
Revises: cf387deb0de2
Create Date: 2026-08-08 13:00:57.297699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c903caf2dcff'
down_revision = 'cf387deb0de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'officer_id', 'assignment_type', 'effective_date', name='uq_officer_assignment')
    )
    with op.batch_alter_table('officer_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officer_assignments_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_assignments_assignment_type'), ['assignment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_assignments_officer_id'), ['officer_id'], unique=False)

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('officer_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officer_assignments_officer_id'))
        batch_op.drop_index(batch_op.f('ix_officer_assignments_assignment_type'))
        batch_op.drop_index(batch_op.f('ix_officer_assignments_agency_id'))

    op.drop_table('officer_assignments')
    # ### end Alembic commands ###
