"""add telecommunicator service date

Revision ID: cee5a16f19c2
Revises: 9fc44bb0643f
Create Date: 2026-08-11 11:23:01.156108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee5a16f19c2'
down_revision = '9fc44bb0643f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telecommunicator_service_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('telecommunicator_service_start_date')

    # ### end Alembic commands ###
