"""v0.2.0 add three-file TCOLE import tracking

Revision ID: cf387deb0de2
Revises: 1fda256cca0e
Create Date: 2026-08-08 11:54:12.469115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf387deb0de2'
down_revision = '1fda256cca0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cycle_rows_processed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('training_records_with_hours', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('training_records_with_hours')
        batch_op.drop_column('cycle_rows_processed')
        batch_op.drop_column('cycle_filename')

    # ### end Alembic commands ###
