"""v0.4.7 add college credit hours qualification

Revision ID: d196164c0a55
Revises: 7a2d9f4c81e6
Create Date: 2026-08-13 13:54:27.307296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd196164c0a55'
down_revision = '7a2d9f4c81e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_college_credit_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('verified_college_credit_hours')

    # ### end Alembic commands ###
