"""v0.2.24 add license compliance tracking

Revision ID: dd8e524c8cff
Revises: f6b1a2c3d4e5
Create Date: 2026-08-12 15:43:04.121079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e524c8cff'
down_revision = 'f6b1a2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_license_tracking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('license_type', sa.String(length=30), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_disabled_by', sa.String(length=255), nullable=True),
    sa.Column('last_disabled_reason', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'officer_id', 'license_type', name='uq_officer_license_tracking')
    )
    with op.batch_alter_table('officer_license_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officer_license_tracking_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_license_tracking_license_type'), ['license_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_license_tracking_officer_id'), ['officer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_license_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officer_license_tracking_officer_id'))
        batch_op.drop_index(batch_op.f('ix_officer_license_tracking_license_type'))
        batch_op.drop_index(batch_op.f('ix_officer_license_tracking_agency_id'))

    op.drop_table('officer_license_tracking')
    # ### end Alembic commands ###
