"""v0.4.8 add military service training credit

Revision ID: e487caec26cd
Revises: d196164c0a55
Create Date: 2026-08-13 14:13:03.750851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e487caec26cd'
down_revision = 'd196164c0a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_military_training_credit_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('verified_military_training_credit_hours')

    # ### end Alembic commands ###
