"""v0.1.4 add training records

Revision ID: f81baec4d098
Revises: 4882e6f4c3c8
Create Date: 2026-08-08 11:29:51.034483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81baec4d098'
down_revision = '4882e6f4c3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('course_number', sa.String(length=50), nullable=False),
    sa.Column('course_title', sa.String(length=500), nullable=False),
    sa.Column('course_date', sa.Date(), nullable=False),
    sa.Column('plus_course_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'officer_id', 'course_number', 'course_title', 'course_date', 'plus_course_id', name='uq_training_record')
    )
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_records_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_records_course_date'), ['course_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_records_officer_id'), ['officer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_records_officer_id'))
        batch_op.drop_index(batch_op.f('ix_training_records_course_date'))
        batch_op.drop_index(batch_op.f('ix_training_records_agency_id'))

    op.drop_table('training_records')
    # ### end Alembic commands ###
